### ISSUE TITLE
Having trouble building `npm run build`

### ISSUE THREAD

**Issue by arjunkalburgi** [rodneylab/sveltekit-blog-mdx#2]
**Describe the bug**
Hey I'm not able to build the repo properly. 

**To Reproduce**
These are the steps I took:

1. git clone into a new folder 
2. run `npm i` => got error that my node version needed to be upgraded
3. run `brew install node` (node version now v17.3.0)
4. run `npm i` (worked) 
5. run `npm run dev` (worked) 
6. run `npm run preview` (worked) 
7. run `npm run build` 

**Expected behaviour**
Just want the repo to build with all the styles and JS. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8989414/147993215-8afb3523-dac6-4410-9931-2de25204c2fc.png)
![image](https://user-images.githubusercontent.com/8989414/147993271-ad6f640b-80cd-4191-925a-41327787fa10.png)

Looks like

**Desktop (please complete the following information):**

- OS: Mac 11.2.3
- Browser n/a
- Version just cloned it

**Additional context**

**Comment by rodneylab** [comment]
Hi Arjun, thanks for reaching out.  At a first glance, it might be related to breaking changes in SvelteKit.  I updated the repo yesterday, but did you clone it earlier?  If so would you be able to try on the latest version (or make changes in line [with this commit)](https://github.com/rodneylab/sveltekit-blog-mdx/commit/b98374426cf2cc7e43cdec61ab98feb6feaf07bd) and let me know if it works or not?

**Comment by arjunkalburgi** [comment]
Hey Rodney, it was my fault actually :/ I didn't have a proper adapter. Apparently svelte's static-adapter doesn't actually build it with CSS and JS.
